
public class Exception1 
{
public static void main(String args[])
{
	int num=10,a=0;
	System.out.println(num/a);
	System.out.println(" after exception");
	}
}
